<?php
/*
 +--------------------------------------------------------------------------------+
 | plugins/force_password_change/localization/<lang>.inc                 |
 |                                                                                                     |
 | Localization file of the force password change plugin                    |
 |                                                                                                     |
 | @version 1.0                                                                                 |
 | @author WAINLAKE <michael@wainlake.com>                               |
 +--------------------------------------------------------------------------------+
*/
$labels['title'] = "Please change your password";
$labels['policy'] = "You must change your mailbox password per %d days as our security policy demands.New password cannot be same as old password.";
$labels['lastchange'] = "Time of the last change：";
$labels['hint'] = "Now click right button to change your passowrd.";
$labels['go'] = "Change Password";

$messages['passwordbrokenpolicy'] = 'New password cannot be same as old password.';
?>