<?php
/*
 +--------------------------------------------------------------------------------+
 | plugins/force_password_change/localization/<lang>.inc                 |
 |                                                                                                     |
 | Localization file of the force password change plugin                    |
 |                                                                                                     |
 | @version 1.0                                                                                 |
 | @author WAINLAKE <michael@wainlake.com>                               |
 +--------------------------------------------------------------------------------+
*/
$labels['title'] = "请修改邮箱密码";
$labels['policy'] = "根据安全策略需要，你必须每 %d 天修改你的邮箱密码。<br>新密码不得与旧密码相同。";
$labels['lastchange'] = "最近修改密码时间为：";
$labels['hint'] = "点击右方按钮去修改密码。";
$labels['go'] = "修改密码";

$messages['passwordbrokenpolicy'] = '新密码不得与旧密码相同。';
?>