<?php
/*
 +--------------------------------------------------------------------------------+
 | plugins/force_password_change/localization/<lang>.inc                 |
 |                                                                                                     |
 | Localization file of the force password change plugin                    |
 |                                                                                                     |
 | @version 1.0                                                                                 |
 | @author WAINLAKE <michael@wainlake.com>                               |
 +--------------------------------------------------------------------------------+
*/
$labels['title'] = "請修改郵箱密碼";
$labels['policy'] = "根據安全性原則需要，你必須每 %d 天修改你的郵箱密碼。<br>新密碼不得與舊密碼相同。";
$labels['lastchange'] = "最近修改密碼時間為：";
$labels['hint'] = "點擊右方按鈕去修改密碼。";
$labels['go'] = "修改密碼";

$messages['passwordbrokenpolicy'] = '新密碼不得與舊密碼相同。';
?>